=== cqjjjzr/LyricsXML/src/main/resources/LXML_0.0.1.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.github.com/cqjjjzr/LyricsXML"
xmlns="http://www.github.com/cqjjjzr/LyricsXML"
elementFormDefault="qualified">
	<xs:element name="lyrics">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="xs:string" minOccurs="0"/>
				<xs:element name="artist" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="album" type="xs:string" minOccurs="0"/>
				<xs:element name="lang" type="xs:string" minOccurs="0"/>
				<xs:element name="offsetMs" type="xs:integer" minOccurs="0"/>
				<xs:element name="metas" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="meta" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="name" type="xs:string" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="lines" minOccurs="0">
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element name="line" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:all>
										<xs:element name="text" type="richText" />
										<xs:element name="translation" minOccurs="0">
											<xs:complexType>
												<xs:complexContent>
													<xs:extension base="richText">
														<xs:attribute name="lang" type="xs:string" />
													</xs:extension>
												</xs:complexContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="time" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern value="(\d+,\d+;)*"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:all>
									<xs:attribute name="timeMs" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:integer">
												<xs:minInclusive value="0"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="split">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="timeMs" use="required">
												<xs:simpleType>
													<xs:restriction base="xs:integer">
														<xs:minInclusive value="0"/>
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>

			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="richText" mixed="true">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="ruby">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="v" type="xs:string" />
						</xs:extension>     
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:complexType>
</xs:schema>

=== cqjjjzr/LyricsXML/src/test/resources/badTimeInCharacter2.xml
<?xml version="1.0" encoding="UTF-8"?>
<lyrics xmlns="http://www.github.com/cqjjjzr/EnhancedLyrics"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://www.github.com/cqjjjzr/EnhancedLyrics LXML_0.0.1.xsd">
	<title>千ノ縁</title>
	<artist>Yonder Voice</artist>
	<artist>瑶山百霊</artist>
	<album>千ノ縁</album>
	<lang>jp_JP</lang>
	<offsetMs>5</offsetMs>
	<line timeMs="500">
		<text><ruby v="そら">空</ruby>に<ruby v="む">向</ruby>かう</text>
		<time>0,0,0;1,5,0;</time>
		<translation lang="zh_CN">夜樱烂漫</translation>
	</line>
</lyrics>

=== cqjjjzr/LyricsXML/src/test/resources/missingText.xml
<?xml version="1.0" encoding="UTF-8"?>
<lyrics xmlns="http://www.github.com/cqjjjzr/LyricsXML"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://www.github.com/cqjjjzr/EnhancedLyrics LXML_0.0.1.xsd">
	<title>千ノ縁</title>
	<artist>Yonder Voice</artist>
	<artist>瑶山百霊</artist>
	<album>千ノ縁</album>
	<lang>jp_JP</lang>
	<offsetMs>5</offsetMs>
	<lines>
		<line timeMs="500">
			<time>0,0,0;1,150,225;2,250,300;3,350,300;4,400,500;</time>
			<translation lang="zh_CN">夜樱烂漫</translation>
		</line>
	</lines>
</lyrics>

=== cqjjjzr/LyricsXML/src/test/resources/badTimeInCharacter.xml
<?xml version="1.0" encoding="UTF-8"?>
<lyrics xmlns="http://www.github.com/cqjjjzr/LyricsXML"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://www.github.com/cqjjjzr/LyricsXML LXML_0.0.1.xsd">
	<title>千ノ縁</title>
	<artist>Yonder Voice</artist>
	<artist>瑶山百霊</artist>
	<album>千ノ縁</album>
	<lang>jp</lang>
	<offsetMs>5</offsetMs>
	<lines>
		<line timeMs="500">
			<text><ruby v="そら">空</ruby>に<ruby v="む">向</ruby>かう</text>
			<time>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</time>
			<translation lang="zh">夜樱烂漫</translation>
		</line>
	</lines>
</lyrics>

=== cqjjjzr/LyricsXML/src/test/resources/full.xml
<?xml version="1.0" encoding="UTF-8"?>
<lyrics xmlns="http://www.github.com/cqjjjzr/LyricsXML"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://www.github.com/cqjjjzr/LyricsXML LXML_0.0.1.xsd">
	<title>千ノ縁</title>
	<artist>Yonder Voice</artist>
	<artist>瑶山百霊</artist>
	<album>千ノ縁</album>
	<lang>jp</lang>
	<offsetMs>5</offsetMs>
	<lines>
		<line timeMs="500">
			<text><ruby v="そら">空</ruby>に<ruby v="む">向</ruby>かう</text>
			<time>1,150;2,300;3,400;4,500;6,700;</time>
			<translation lang="zh">夜樱烂漫</translation>
		</line>
		<split timeMs="501"/>
		<line timeMs="600">
			<text><ruby v="らんまん">爛漫</ruby>たる<ruby v="よ">夜</ruby><ruby v="さくら">桜</ruby></text>
			<translation lang="zh">朝向天空绽放</translation>
		</line>
	</lines>
</lyrics>
